apiVersion: v1
kind: Service
metadata:
  name: {{ include "openldap.fullname" . }}
  namespace: {{ include "openldap.namespace" . }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "openldap.selectorLabels" . | nindent 4 }}
  ports:
    - name: ldap
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.ldap.port }}
      protocol: TCP
    {{- if .Values.tls.enabled }}
    - name: ldaps
      port: 636
      targetPort: {{ .Values.tls.port }}
      protocol: TCP
    {{- end }}
  {{- if .Values.service.sessionAffinity.enabled }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinity.timeoutSeconds }}
  {{- end }}